version: '3'

services:
  api-express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' 
     
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
         
networks:
  docker_accessnet:
    external: true