version: "3"
services:
  api-express:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app # Use a dot instead of type: bind for better readability
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: npm run dev

  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: collokeasy
      MYSQL_USER: collokeasy
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ../mysqldata:/var/lib/mysql

    # db_test:
    # image: mysql
    # restart: always
    # container_name: db
    # environment:
    #   MYSQL_ROOT_PASSWORD: password
    #   MYSQL_DATABASE: collokeasy
    #   MYSQL_USER: collokeasy
    #   MYSQL_PASSWORD: password
    # ports:
    #   - 33066:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
