version: "3"

services:
  api-express:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: collokeasy
      MYSQL_USER: collokeasy
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    # volumes:
    #   - ./mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# volumes:
#   mysqldata:
